### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by fancycode** [spreedbox/nextcloud-spreedbox-license-keys#4]
@Peterede just noticed you have added a `.travis.yml`, should I enable Travis for this repository?

**Comment by PeterEdens** [comment]
yes please enable Travis.

**Comment by fancycode** [comment]
It's enabled now and I triggered a first build:
https://travis-ci.org/spreedbox/nextcloud-spreedbox-license-keys/builds/178207744

The build failed to clone branch `stable11` from nextcloud, I think you should either use `stable10` or `master`.
